[package]
name = "libsystemd"
version = "0.1.1-alpha.0"
authors = ["Luca Bruno <lucab@debian.org>"]
license = "MIT/Apache-2.0"
repository = "https://github.com/lucab/libsystemd-rs"
documentation = "https://docs.rs/libsystemd"
description = "A pure-Rust client library to interact with systemd"
keywords = ["systemd", "linux"]
categories = ["api-bindings", "os::unix-apis"]
readme = "README.md"
exclude = [
".gitignore",
".travis.yml",
]

[dependencies]
error-chain = { version = "^0.12.1", default-features = false }
hmac = "0.7"
libc = "0.2"
nix = "0.15"
sha2 = "0.8"
try_or = "0.2"
uuid = { version = "^0.7.4", features = ["serde"] }
serde = "^1.0.91"
serde_derive = "^1.0.91"

[dev-dependencies]
quickcheck = "0.9"

[package.metadata.release]
sign-commit = true
upload-doc = false
disable-publish = true
disable-push = true
pre-release-commit-message = "cargo: libsystemd release {{version}}"
pro-release-commit-message = "cargo: version bump to {{version}}"
tag-message = "libsystemd {{version}}"
